#!/usr/bin/env node
// License audit for the Nerdy AI Hackathon rules (7.6): no GPL, LGPL, AGPL or SSPL anywhere
// in the dependency tree. Reciprocal licenses (MPL, EPL, CDDL, ...) are flagged for review.
// Writes docs/THIRD_PARTY_LICENSES.md for the submission disclosures.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const lockPath = path.join(root, "package-lock.json");
if (!existsSync(lockPath)) {
  console.error("package-lock.json not found. Run `npm install` first.");
  process.exit(1);
}

const lock = JSON.parse(readFileSync(lockPath, "utf8"));
const FORBIDDEN = /\b(AGPL|LGPL|GPL|SSPL)\b/i;
const REVIEW = /\b(MPL|EPL|CDDL|OSL|EUPL|CC-BY-SA)\b/i;
const ATTRIBUTION = /\bCC-BY\b/i;

/** Classifies an SPDX-style expression. An OR expression passes if any option is allowed. */
function classify(license) {
  if (!license) return "unknown";
  const options = String(license)
    .replace(/[()]/g, " ")
    .split(/\s+OR\s+/i)
    .map((option) => option.split(/\s+AND\s+/i).map((part) => part.trim()).filter(Boolean));
  const statuses = options.map((parts) =>
    parts.some((p) => FORBIDDEN.test(p)) ? "forbidden" : parts.some((p) => REVIEW.test(p)) ? "review" : "ok",
  );
  if (statuses.includes("ok")) return "ok";
  if (statuses.includes("review")) return "review";
  return "forbidden";
}

function licenseFromDisk(key) {
  const pkgJson = path.join(root, key, "package.json");
  if (!existsSync(pkgJson)) return undefined;
  const pkg = JSON.parse(readFileSync(pkgJson, "utf8"));
  return typeof pkg.license === "string" ? pkg.license : pkg.license?.type;
}

const rows = [];
for (const [key, entry] of Object.entries(lock.packages ?? {})) {
  if (key === "" || entry.link) continue;
  const name =
    entry.name ??
    (key.includes("node_modules/") ? key.slice(key.lastIndexOf("node_modules/") + "node_modules/".length) : key);
  const license = entry.license ?? licenseFromDisk(key);
  rows.push({
    name,
    version: entry.version ?? "?",
    license: license ?? "UNKNOWN",
    scope: entry.dev ? "dev" : "runtime",
    optional: Boolean(entry.optional),
    status: classify(license),
  });
}

rows.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
const byStatus = (status) => rows.filter((r) => r.status === status);
const forbidden = byStatus("forbidden");
// Reciprocal licenses are allowed by the rules but reviewed when they ship in the app.
// Development tools (linters, test runners) are never distributed with the product.
const needsReview = rows.filter((r) => (r.status === "review" && r.scope === "runtime") || r.status === "unknown");
const devOnlyReciprocal = rows.filter((r) => r.status === "review" && r.scope === "dev");

const counts = new Map();
for (const r of rows) counts.set(r.license, (counts.get(r.license) ?? 0) + 1);

const lines = [
  "# Third-party licenses",
  "",
  `Generated by \`npm run audit:licenses\` from package-lock.json (${rows.length} packages).`,
  "The hackathon rules forbid GPL, LGPL, AGPL and SSPL components; this file is part of the Rule 7.6 disclosures.",
  "",
  "## License summary",
  "",
  "| License | Packages |",
  "|---|---|",
  ...[...counts.entries()].sort((a, b) => b[1] - a[1]).map(([license, n]) => `| ${license} | ${n} |`),
  "",
];
const attribution = rows.filter((r) => ATTRIBUTION.test(r.license));
if (attribution.length) {
  lines.push("## Attribution required", "", ...attribution.map((r) => `- ${r.name}@${r.version} (${r.license})`), "");
}
if (devOnlyReciprocal.length) {
  lines.push(
    "## Reciprocal licenses in development tools only",
    "",
    "Used only for linting and testing; not bundled into or distributed with the app.",
    "",
    ...devOnlyReciprocal.map((r) => `- ${r.name}@${r.version} (${r.license})`),
    "",
  );
}
lines.push(
  "## All packages",
  "",
  "| Package | Version | License | Scope |",
  "|---|---|---|---|",
  ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} | ${r.scope}${r.optional ? " (optional)" : ""} |`),
  "",
);

mkdirSync(path.join(root, "docs"), { recursive: true });
writeFileSync(path.join(root, "docs", "THIRD_PARTY_LICENSES.md"), lines.join("\n"));

console.log(`Audited ${rows.length} packages. Report: docs/THIRD_PARTY_LICENSES.md`);
for (const r of devOnlyReciprocal) console.log(`INFO    dev tool only (not shipped) ${r.name}@${r.version}: ${r.license}`);
for (const r of needsReview) console.warn(`REVIEW  ${r.name}@${r.version}: ${r.license}`);
if (forbidden.length) {
  for (const r of forbidden) console.error(`FORBIDDEN  ${r.name}@${r.version}: ${r.license}`);
  process.exit(1);
}
console.log("No forbidden licenses found.");
